// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Applicant struct {
	ID        int64      `json:"id"`
	User      *User      `json:"user,omitempty"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Application struct {
	ID        int64      `json:"id"`
	Applicant *Applicant `json:"applicant,omitempty"`
	Job       *Job       `json:"job,omitempty"`
	Status    string     `json:"status"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Company struct {
	ID          int64      `json:"id"`
	User        *User      `json:"user,omitempty"`
	CompanyName string     `json:"companyName"`
	Website     string     `json:"website"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type Job struct {
	ID           int64      `json:"id"`
	Company      *Company   `json:"company,omitempty"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Requirements []string   `json:"requirements"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

type Mutation struct {
}

type MutationContent struct {
	ID          int64      `json:"id"`
	ContentType string     `json:"contentType"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type MutationResponse struct {
	StatusOk int              `json:"statusOK"`
	Stats    *MutationStats   `json:"stats,omitempty"`
	Data     *MutationContent `json:"data,omitempty"`
	Error    *string          `json:"error,omitempty"`
}

type MutationStats struct {
	UpdateCount *int `json:"updateCount,omitempty"`
	DeleteCount *int `json:"deleteCount,omitempty"`
}

type NewApplicant struct {
	User *NewUser `json:"user"`
}

type NewApplication struct {
	ApplicantID int64 `json:"applicantId"`
	JobID       int64 `json:"jobId"`
}

type NewCompany struct {
	User        *NewUser `json:"user"`
	CompanyName string   `json:"companyName"`
	Description string   `json:"description"`
	Website     string   `json:"website"`
}

type NewJob struct {
	CompanyID    int64    `json:"companyId"`
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Requirements []string `json:"requirements"`
}

type NewUser struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}

type Query struct {
}

type UpdateApplication struct {
	Status    string     `json:"status"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type UpdateCompany struct {
	CompanyName *string    `json:"companyName,omitempty"`
	Description *string    `json:"description,omitempty"`
	Website     *string    `json:"website,omitempty"`
	UpdatedAt   *time.Time `json:"updatedAt,omitempty"`
}

type UpdateJob struct {
	Title        *string    `json:"title,omitempty"`
	Description  *string    `json:"description,omitempty"`
	Requirements []string   `json:"requirements"`
	UpdatedAt    *time.Time `json:"updatedAt,omitempty"`
}

type UpdateUser struct {
	Name      string     `json:"name"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type User struct {
	ID        int64      `json:"id"`
	Username  string     `json:"username"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}
