// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Applicant struct {
	ID        int64      `json:"id"`
	User      *User      `json:"user"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Application struct {
	ID        int64      `json:"id"`
	Applicant *Applicant `json:"applicant"`
	Job       *Job       `json:"job"`
	Status    string     `json:"status"`
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt time.Time  `json:"updatedAt"`
	DeletedAt *time.Time `json:"deletedAt,omitempty"`
}

type Company struct {
	ID          int64      `json:"id"`
	User        *User      `json:"user"`
	CompanyName string     `json:"companyName"`
	Website     string     `json:"website"`
	Description string     `json:"description"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	DeletedAt   *time.Time `json:"deletedAt,omitempty"`
}

type DeletionStatus struct {
	Status string  `json:"status"`
	Data   any     `json:"data,omitempty"`
	Error  *string `json:"error,omitempty"`
}

type Job struct {
	ID           int64      `json:"id"`
	Company      *Company   `json:"company"`
	Title        string     `json:"title"`
	Description  string     `json:"description"`
	Requirements []string   `json:"requirements"`
	CreatedAt    time.Time  `json:"createdAt"`
	UpdatedAt    time.Time  `json:"updatedAt"`
	DeletedAt    *time.Time `json:"deletedAt,omitempty"`
}

type Mutation struct {
}

type NewApplicant struct {
	User *NewUser `json:"user"`
}

type NewApplication struct {
	ApplicantID int64 `json:"applicantId"`
	JobID       int64 `json:"jobId"`
}

type NewCompany struct {
	User        *NewUser `json:"user"`
	CompanyName string   `json:"companyName"`
	Description string   `json:"description"`
	Website     string   `json:"website"`
}

type NewJob struct {
	CompanyID    int64    `json:"companyId"`
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Requirements []string `json:"requirements"`
}

type NewUser struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}

type Query struct {
}

type UpdateApplication struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

type UpdateCompany struct {
	ID          int64  `json:"id"`
	CompanyName string `json:"companyName"`
	Description string `json:"description"`
	Website     string `json:"website"`
}

type UpdateJob struct {
	ID           int64    `json:"id"`
	Title        string   `json:"title"`
	Description  string   `json:"description"`
	Requirements []string `json:"requirements"`
}

type UpdateUser struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type User struct {
	ID        int64      `json:"id"`
	Username  string     `json:"username"`
	Name      string     `json:"name"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
}
