// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"context"
	"errors"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/introspection"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{
		schema:     cfg.Schema,
		resolvers:  cfg.Resolvers,
		directives: cfg.Directives,
		complexity: cfg.Complexity,
	}
}

type Config struct {
	Schema     *ast.Schema
	Resolvers  ResolverRoot
	Directives DirectiveRoot
	Complexity ComplexityRoot
}

type ResolverRoot interface {
	Applicant() ApplicantResolver
	Application() ApplicationResolver
	Company() CompanyResolver
	Job() JobResolver
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Applicant struct {
		CreatedAt func(childComplexity int) int
		DeletedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		User      func(childComplexity int) int
	}

	Application struct {
		Applicant func(childComplexity int) int
		CreatedAt func(childComplexity int) int
		DeletedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		Job       func(childComplexity int) int
		Status    func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
	}

	Company struct {
		CompanyName func(childComplexity int) int
		CreatedAt   func(childComplexity int) int
		DeletedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
		User        func(childComplexity int) int
		Website     func(childComplexity int) int
	}

	DeletionStatus struct {
		Data   func(childComplexity int) int
		Error  func(childComplexity int) int
		Status func(childComplexity int) int
	}

	Job struct {
		Company      func(childComplexity int) int
		CreatedAt    func(childComplexity int) int
		DeletedAt    func(childComplexity int) int
		Description  func(childComplexity int) int
		ID           func(childComplexity int) int
		Requirements func(childComplexity int) int
		Title        func(childComplexity int) int
		UpdatedAt    func(childComplexity int) int
	}

	Mutation struct {
		CreateApplicant       func(childComplexity int, input NewApplicant) int
		CreateApplication     func(childComplexity int, input NewApplication) int
		CreateCompany         func(childComplexity int, input NewCompany) int
		CreateJob             func(childComplexity int, input NewJob) int
		CreateUser            func(childComplexity int, input NewUser) int
		DeleteApplicantByID   func(childComplexity int, input int64) int
		DeleteApplicationByID func(childComplexity int, input int64) int
		DeleteCompanyByID     func(childComplexity int, input int64) int
		DeleteJobByID         func(childComplexity int, input int64) int
		DeleteUserByID        func(childComplexity int, input int64) int
		UpdateApplicationByID func(childComplexity int, input UpdateApplication) int
		UpdateCompanyByID     func(childComplexity int, input UpdateCompany) int
		UpdateJobByID         func(childComplexity int, input UpdateJob) int
		UpdateUserByID        func(childComplexity int, input UpdateUser) int
	}

	Query struct {
		Applicants                func(childComplexity int) int
		Applications              func(childComplexity int) int
		ApplicationsByApplicantID func(childComplexity int, applicantID int64) int
		ApplicationsByJobID       func(childComplexity int, jobID int64) int
		Companies                 func(childComplexity int) int
		Jobs                      func(childComplexity int) int
		JobsByCompanyID           func(childComplexity int, companyID int64) int
		Users                     func(childComplexity int) int
	}

	User struct {
		CreatedAt func(childComplexity int) int
		DeletedAt func(childComplexity int) int
		ID        func(childComplexity int) int
		Name      func(childComplexity int) int
		UpdatedAt func(childComplexity int) int
		Username  func(childComplexity int) int
	}
}

type executableSchema struct {
	schema     *ast.Schema
	resolvers  ResolverRoot
	directives DirectiveRoot
	complexity ComplexityRoot
}

func (e *executableSchema) Schema() *ast.Schema {
	if e.schema != nil {
		return e.schema
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := executionContext{nil, e, 0, 0, nil}
	_ = ec
	switch typeName + "." + field {

	case "Applicant.createdAt":
		if e.complexity.Applicant.CreatedAt == nil {
			break
		}

		return e.complexity.Applicant.CreatedAt(childComplexity), true

	case "Applicant.deletedAt":
		if e.complexity.Applicant.DeletedAt == nil {
			break
		}

		return e.complexity.Applicant.DeletedAt(childComplexity), true

	case "Applicant.id":
		if e.complexity.Applicant.ID == nil {
			break
		}

		return e.complexity.Applicant.ID(childComplexity), true

	case "Applicant.updatedAt":
		if e.complexity.Applicant.UpdatedAt == nil {
			break
		}

		return e.complexity.Applicant.UpdatedAt(childComplexity), true

	case "Applicant.user":
		if e.complexity.Applicant.User == nil {
			break
		}

		return e.complexity.Applicant.User(childComplexity), true

	case "Application.applicant":
		if e.complexity.Application.Applicant == nil {
			break
		}

		return e.complexity.Application.Applicant(childComplexity), true

	case "Application.createdAt":
		if e.complexity.Application.CreatedAt == nil {
			break
		}

		return e.complexity.Application.CreatedAt(childComplexity), true

	case "Application.deletedAt":
		if e.complexity.Application.DeletedAt == nil {
			break
		}

		return e.complexity.Application.DeletedAt(childComplexity), true

	case "Application.id":
		if e.complexity.Application.ID == nil {
			break
		}

		return e.complexity.Application.ID(childComplexity), true

	case "Application.job":
		if e.complexity.Application.Job == nil {
			break
		}

		return e.complexity.Application.Job(childComplexity), true

	case "Application.status":
		if e.complexity.Application.Status == nil {
			break
		}

		return e.complexity.Application.Status(childComplexity), true

	case "Application.updatedAt":
		if e.complexity.Application.UpdatedAt == nil {
			break
		}

		return e.complexity.Application.UpdatedAt(childComplexity), true

	case "Company.companyName":
		if e.complexity.Company.CompanyName == nil {
			break
		}

		return e.complexity.Company.CompanyName(childComplexity), true

	case "Company.createdAt":
		if e.complexity.Company.CreatedAt == nil {
			break
		}

		return e.complexity.Company.CreatedAt(childComplexity), true

	case "Company.deletedAt":
		if e.complexity.Company.DeletedAt == nil {
			break
		}

		return e.complexity.Company.DeletedAt(childComplexity), true

	case "Company.description":
		if e.complexity.Company.Description == nil {
			break
		}

		return e.complexity.Company.Description(childComplexity), true

	case "Company.id":
		if e.complexity.Company.ID == nil {
			break
		}

		return e.complexity.Company.ID(childComplexity), true

	case "Company.updatedAt":
		if e.complexity.Company.UpdatedAt == nil {
			break
		}

		return e.complexity.Company.UpdatedAt(childComplexity), true

	case "Company.user":
		if e.complexity.Company.User == nil {
			break
		}

		return e.complexity.Company.User(childComplexity), true

	case "Company.website":
		if e.complexity.Company.Website == nil {
			break
		}

		return e.complexity.Company.Website(childComplexity), true

	case "DeletionStatus.data":
		if e.complexity.DeletionStatus.Data == nil {
			break
		}

		return e.complexity.DeletionStatus.Data(childComplexity), true

	case "DeletionStatus.error":
		if e.complexity.DeletionStatus.Error == nil {
			break
		}

		return e.complexity.DeletionStatus.Error(childComplexity), true

	case "DeletionStatus.status":
		if e.complexity.DeletionStatus.Status == nil {
			break
		}

		return e.complexity.DeletionStatus.Status(childComplexity), true

	case "Job.company":
		if e.complexity.Job.Company == nil {
			break
		}

		return e.complexity.Job.Company(childComplexity), true

	case "Job.createdAt":
		if e.complexity.Job.CreatedAt == nil {
			break
		}

		return e.complexity.Job.CreatedAt(childComplexity), true

	case "Job.deletedAt":
		if e.complexity.Job.DeletedAt == nil {
			break
		}

		return e.complexity.Job.DeletedAt(childComplexity), true

	case "Job.description":
		if e.complexity.Job.Description == nil {
			break
		}

		return e.complexity.Job.Description(childComplexity), true

	case "Job.id":
		if e.complexity.Job.ID == nil {
			break
		}

		return e.complexity.Job.ID(childComplexity), true

	case "Job.requirements":
		if e.complexity.Job.Requirements == nil {
			break
		}

		return e.complexity.Job.Requirements(childComplexity), true

	case "Job.title":
		if e.complexity.Job.Title == nil {
			break
		}

		return e.complexity.Job.Title(childComplexity), true

	case "Job.updatedAt":
		if e.complexity.Job.UpdatedAt == nil {
			break
		}

		return e.complexity.Job.UpdatedAt(childComplexity), true

	case "Mutation.createApplicant":
		if e.complexity.Mutation.CreateApplicant == nil {
			break
		}

		args, err := ec.field_Mutation_createApplicant_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateApplicant(childComplexity, args["input"].(NewApplicant)), true

	case "Mutation.createApplication":
		if e.complexity.Mutation.CreateApplication == nil {
			break
		}

		args, err := ec.field_Mutation_createApplication_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateApplication(childComplexity, args["input"].(NewApplication)), true

	case "Mutation.createCompany":
		if e.complexity.Mutation.CreateCompany == nil {
			break
		}

		args, err := ec.field_Mutation_createCompany_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateCompany(childComplexity, args["input"].(NewCompany)), true

	case "Mutation.createJob":
		if e.complexity.Mutation.CreateJob == nil {
			break
		}

		args, err := ec.field_Mutation_createJob_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateJob(childComplexity, args["input"].(NewJob)), true

	case "Mutation.createUser":
		if e.complexity.Mutation.CreateUser == nil {
			break
		}

		args, err := ec.field_Mutation_createUser_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.CreateUser(childComplexity, args["input"].(NewUser)), true

	case "Mutation.deleteApplicantById":
		if e.complexity.Mutation.DeleteApplicantByID == nil {
			break
		}

		args, err := ec.field_Mutation_deleteApplicantById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteApplicantByID(childComplexity, args["input"].(int64)), true

	case "Mutation.deleteApplicationById":
		if e.complexity.Mutation.DeleteApplicationByID == nil {
			break
		}

		args, err := ec.field_Mutation_deleteApplicationById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteApplicationByID(childComplexity, args["input"].(int64)), true

	case "Mutation.deleteCompanyById":
		if e.complexity.Mutation.DeleteCompanyByID == nil {
			break
		}

		args, err := ec.field_Mutation_deleteCompanyById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteCompanyByID(childComplexity, args["input"].(int64)), true

	case "Mutation.deleteJobById":
		if e.complexity.Mutation.DeleteJobByID == nil {
			break
		}

		args, err := ec.field_Mutation_deleteJobById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteJobByID(childComplexity, args["input"].(int64)), true

	case "Mutation.deleteUserById":
		if e.complexity.Mutation.DeleteUserByID == nil {
			break
		}

		args, err := ec.field_Mutation_deleteUserById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.DeleteUserByID(childComplexity, args["input"].(int64)), true

	case "Mutation.updateApplicationById":
		if e.complexity.Mutation.UpdateApplicationByID == nil {
			break
		}

		args, err := ec.field_Mutation_updateApplicationById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateApplicationByID(childComplexity, args["input"].(UpdateApplication)), true

	case "Mutation.updateCompanyById":
		if e.complexity.Mutation.UpdateCompanyByID == nil {
			break
		}

		args, err := ec.field_Mutation_updateCompanyById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateCompanyByID(childComplexity, args["input"].(UpdateCompany)), true

	case "Mutation.updateJobById":
		if e.complexity.Mutation.UpdateJobByID == nil {
			break
		}

		args, err := ec.field_Mutation_updateJobById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateJobByID(childComplexity, args["input"].(UpdateJob)), true

	case "Mutation.updateUserById":
		if e.complexity.Mutation.UpdateUserByID == nil {
			break
		}

		args, err := ec.field_Mutation_updateUserById_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Mutation.UpdateUserByID(childComplexity, args["input"].(UpdateUser)), true

	case "Query.applicants":
		if e.complexity.Query.Applicants == nil {
			break
		}

		return e.complexity.Query.Applicants(childComplexity), true

	case "Query.applications":
		if e.complexity.Query.Applications == nil {
			break
		}

		return e.complexity.Query.Applications(childComplexity), true

	case "Query.applicationsByApplicantId":
		if e.complexity.Query.ApplicationsByApplicantID == nil {
			break
		}

		args, err := ec.field_Query_applicationsByApplicantId_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ApplicationsByApplicantID(childComplexity, args["applicantId"].(int64)), true

	case "Query.applicationsByJobId":
		if e.complexity.Query.ApplicationsByJobID == nil {
			break
		}

		args, err := ec.field_Query_applicationsByJobId_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.ApplicationsByJobID(childComplexity, args["jobId"].(int64)), true

	case "Query.companies":
		if e.complexity.Query.Companies == nil {
			break
		}

		return e.complexity.Query.Companies(childComplexity), true

	case "Query.jobs":
		if e.complexity.Query.Jobs == nil {
			break
		}

		return e.complexity.Query.Jobs(childComplexity), true

	case "Query.jobsByCompanyId":
		if e.complexity.Query.JobsByCompanyID == nil {
			break
		}

		args, err := ec.field_Query_jobsByCompanyId_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.complexity.Query.JobsByCompanyID(childComplexity, args["companyId"].(int64)), true

	case "Query.users":
		if e.complexity.Query.Users == nil {
			break
		}

		return e.complexity.Query.Users(childComplexity), true

	case "User.created_at":
		if e.complexity.User.CreatedAt == nil {
			break
		}

		return e.complexity.User.CreatedAt(childComplexity), true

	case "User.deleted_at":
		if e.complexity.User.DeletedAt == nil {
			break
		}

		return e.complexity.User.DeletedAt(childComplexity), true

	case "User.id":
		if e.complexity.User.ID == nil {
			break
		}

		return e.complexity.User.ID(childComplexity), true

	case "User.name":
		if e.complexity.User.Name == nil {
			break
		}

		return e.complexity.User.Name(childComplexity), true

	case "User.updated_at":
		if e.complexity.User.UpdatedAt == nil {
			break
		}

		return e.complexity.User.UpdatedAt(childComplexity), true

	case "User.username":
		if e.complexity.User.Username == nil {
			break
		}

		return e.complexity.User.Username(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := executionContext{opCtx, e, 0, 0, make(chan graphql.DeferredResult)}
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputNewApplicant,
		ec.unmarshalInputNewApplication,
		ec.unmarshalInputNewCompany,
		ec.unmarshalInputNewJob,
		ec.unmarshalInputNewUser,
		ec.unmarshalInputUpdateApplication,
		ec.unmarshalInputUpdateCompany,
		ec.unmarshalInputUpdateJob,
		ec.unmarshalInputUpdateUser,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.pendingDeferred) > 0 {
					result := <-ec.deferredResults
					atomic.AddInt32(&ec.pendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.pendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.OperationContext
	*executableSchema
	deferred        int32
	pendingDeferred int32
	deferredResults chan graphql.DeferredResult
}

func (ec *executionContext) processDeferredGroup(dg graphql.DeferredGroup) {
	atomic.AddInt32(&ec.pendingDeferred, 1)
	go func() {
		ctx := graphql.WithFreshResponseContext(dg.Context)
		dg.FieldSet.Dispatch(ctx)
		ds := graphql.DeferredResult{
			Path:   dg.Path,
			Label:  dg.Label,
			Result: dg.FieldSet,
			Errors: graphql.GetErrors(ctx),
		}
		// null fields should bubble up
		if dg.FieldSet.Invalids > 0 {
			ds.Result = graphql.Null
		}
		ec.deferredResults <- ds
	}()
}

func (ec *executionContext) introspectSchema() (*introspection.Schema, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapSchema(ec.Schema()), nil
}

func (ec *executionContext) introspectType(name string) (*introspection.Type, error) {
	if ec.DisableIntrospection {
		return nil, errors.New("introspection disabled")
	}
	return introspection.WrapTypeFromDef(ec.Schema(), ec.Schema().Types[name]), nil
}

var sources = []*ast.Source{
	{Name: "../jobhunt-mutations.schema.graphqls", Input: `# GraphQL schema example
#
# https://gqlgen.com/getting-started/


type Mutation {
  createJob(input: NewJob!): Job
  createCompany(input: NewCompany!): Company
  createApplicant(input: NewApplicant!): Applicant
  createUser(input: NewUser!): User
  createApplication(input: NewApplication!): Application

  # TODO: refactor, extract id from update object
  updateJobById(input: UpdateJob!): Job
  updateCompanyById(input: UpdateCompany!): Company
  updateUserById(input: UpdateUser!): User
  updateApplicationById(input: UpdateApplication!): Application

  deleteJobById(input: ID!): DeletionStatus
  deleteCompanyById(input: ID!): DeletionStatus
  deleteApplicantById(input: ID!): DeletionStatus
  deleteUserById(input: ID!): DeletionStatus
  deleteApplicationById(input: ID!): DeletionStatus
}

type Query {
  jobs: [Job!]!
  companies: [Company!]!
  applicants: [Applicant!]!
  applications: [Application!]!
  users: [User!]!
  applicationsByApplicantId(applicantId: ID!): [Application!]!
  applicationsByJobId(jobId: ID!): [Application!]!
  jobsByCompanyId(companyId: ID!): [Job!]!
}
`, BuiltIn: false},
	{Name: "../jobhunt.schema.graphqls", Input: `# GraphQL schema example
#
# https://gqlgen.com/getting-started/

scalar Time
scalar Any
directive @goField(
  forceResolver: Boolean
  name: String
) on FIELD_DEFINITION | INPUT_FIELD_DEFINITION


input UpdateJob {
  id:           ID!
  title:        String!
  description:  String!
  requirements: [String!]!
}

input UpdateCompany {
  id:          ID!
  companyName: String!
  description: String!
  website:     String!
}

input UpdateApplication {
  id:     ID!
  status: String!
}

input UpdateUser {
  id:   ID!
  name: String!
}

type User {
  id: ID!
  username: String!
  name: String!
  created_at: Time!
  updated_at: Time!
  deleted_at: Time
}

type Applicant {
  id: ID!
  user: User @goField(forceResolver: true)
  createdAt: Time!
  updatedAt: Time!
  deletedAt: Time
}

type Company {
  id:           ID!
  user:         User @goField(forceResolver: true)
  companyName:  String!
  website:      String!
  description:  String!
  createdAt:    Time!
  updatedAt:    Time!
  deletedAt:    Time
}

type Job {
  id:           ID!
  company:      Company @goField(forceResolver: true)
  title:        String!
  description:  String!
  requirements: [String!]!
  createdAt:    Time!
  updatedAt:    Time!
  deletedAt:    Time
}

type Application {
  id:          ID!
  applicant:   Applicant @goField(forceResolver: true)
  job:         Job @goField(forceResolver: true)
  status:      String!
  createdAt:   Time!
  updatedAt:   Time!
  deletedAt:   Time
}

type DeletionStatus {
  status: String!
  data: Any
  error: String
}


input NewJob {
  companyId: ID!
  title: String!
  description: String!
  requirements: [String!]!
}

input NewCompany {
  user: NewUser!
  companyName: String!
  description: String!
  website: String!
}

input NewApplicant {
  user: NewUser!
}

input NewApplication {
  applicantId: ID!
  jobId: ID!
}

input NewUser {
  username: String!
  name: String!
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)
