package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"fmt"
	"log"

	gqlModel "github.com/ni-tami/job-hunting-dummies-service/internal/graphql/model"
	"github.com/ni-tami/job-hunting-dummies-service/internal/model"
)

// CreateJob is the resolver for the createJob field for existing company
func (r *mutationResolver) CreateJob(ctx context.Context, input gqlModel.NewJob) (*gqlModel.Job, error) {
	dbJob, err := r.jobPortalUsecase.CreateJob(ctx, input)
	if err != nil {
		log.Fatal("Failed to create job")
	}
	job := dbJob.ToGQL()
	return job, nil
}

// CreateCompany is the resolver for the createCompany field.
func (r *mutationResolver) CreateCompany(ctx context.Context, input gqlModel.NewCompany) (*gqlModel.Company, error) {
	dbCompany, err := r.jobPortalUsecase.CreateCompany(ctx, input)
	if err != nil {
		log.Fatal("Failed to create company")
	}
	company := dbCompany.ToGQL()
	return company, nil
}

// CreateApplicant is the resolver for the createApplicant field.
func (r *mutationResolver) CreateApplicant(ctx context.Context, input gqlModel.NewApplicant) (*gqlModel.Applicant, error) {
	dbApplicant, err := r.jobPortalUsecase.CreateApplicant(ctx, input)
	if err != nil {
		log.Fatal("Failed to create applicant")
	}
	applicant := dbApplicant.ToGQL()
	return applicant, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqlModel.NewUser) (*gqlModel.User, error) {
	createUserPayload := model.NewUserCreateFromGQL(input)
	dbUser, err := r.jobPortalUsecase.CreateUser(ctx, createUserPayload)
	if err != nil {
		log.Fatal("Failed to create user")
	}
	user := dbUser.ToGQL()
	return user, nil
}

// CreateApplication is the resolver for the createApplication field.
func (r *mutationResolver) CreateApplication(ctx context.Context, input gqlModel.NewApplication) (*gqlModel.Application, error) {
	dbApplication, err := r.jobPortalUsecase.CreateApplication(ctx, input)
	if err != nil {
		log.Fatal("Failed to create application")
	}
	application := dbApplication.ToGQL()
	return application, nil
}

// UpdateJobByID is the resolver for the updateJobById field.
func (r *mutationResolver) UpdateJobByID(ctx context.Context, id int64, job gqlModel.UpdateJob) (*gqlModel.MutationResponse, error) {
	response := r.jobPortalUsecase.UpdateJobByID(ctx, id, &job)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to update job with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				UpdateCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Job",
				UpdatedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// UpdateCompanyByID is the resolver for the updateCompanyById field.
func (r *mutationResolver) UpdateCompanyByID(ctx context.Context, id int64, company gqlModel.UpdateCompany) (*gqlModel.MutationResponse, error) {
	response := r.jobPortalUsecase.UpdateCompanyByID(ctx, id, &company)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to update company with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				UpdateCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Company",
				UpdatedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// UpdateUserByID is the resolver for the updateUserById field.
func (r *mutationResolver) UpdateUserByID(ctx context.Context, id int64, user gqlModel.UpdateUser) (*gqlModel.MutationResponse, error) {
	response := r.jobPortalUsecase.UpdateUserByID(ctx, id, &user)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to update user with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				UpdateCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "User",
				UpdatedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// UpdateApplicationByID is the resolver for the updateApplicationById field.
func (r *mutationResolver) UpdateApplicationByID(ctx context.Context, id int64, application gqlModel.UpdateApplication) (*gqlModel.MutationResponse, error) {
	response := r.jobPortalUsecase.UpdateApplicationByID(ctx, id, &application)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to update application with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				UpdateCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Application",
				UpdatedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// DeleteJobByID is the resolver for the deleteJobById field.
func (r *mutationResolver) DeleteJobByID(ctx context.Context, id int64) (*gqlModel.MutationResponse, error) {
	// TODO cascade soft delete to applicants
	response := r.jobPortalUsecase.DeleteJobByID(ctx, id)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to delete job with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				DeleteCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Job",
				UpdatedAt:   response.UpdatedAt,
				DeletedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// DeleteCompanyByID is the resolver for the deleteCompanyById field.
func (r *mutationResolver) DeleteCompanyByID(ctx context.Context, id int64) (*gqlModel.MutationResponse, error) {
	// TODO cascade soft delete jobs - applications
	response := r.jobPortalUsecase.DeleteCompanyByID(ctx, id)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to delete company with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				DeleteCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Company",
				UpdatedAt:   response.UpdatedAt,
				DeletedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// DeleteApplicantByID is the resolver for the deleteApplicantById field.
func (r *mutationResolver) DeleteApplicantByID(ctx context.Context, id int64) (*gqlModel.MutationResponse, error) {
	// TODO cascade soft delete to application and user
	response := r.jobPortalUsecase.DeleteApplicantByID(ctx, id)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to delete applicant with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				DeleteCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Applicant",
				UpdatedAt:   response.UpdatedAt,
				DeletedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// DeleteUserByID is the resolver for the deleteUserById field.
func (r *mutationResolver) DeleteUserByID(ctx context.Context, id int64) (*gqlModel.MutationResponse, error) {
	// TODO cascade soft delete to user
	response := r.jobPortalUsecase.DeleteUserByID(ctx, id)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to delete user with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				DeleteCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "User",
				UpdatedAt:   response.UpdatedAt,
				DeletedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// DeleteApplicationByID is the resolver for the deleteApplicationById field.
func (r *mutationResolver) DeleteApplicationByID(ctx context.Context, id int64) (*gqlModel.MutationResponse, error) {
	response := r.jobPortalUsecase.DeleteApplicationByID(ctx, id)

	var (
		err              error
		mutationResponse *gqlModel.MutationResponse
	)
	if response.Err != nil {
		errMessage := fmt.Sprintf("Failed to delete application with ID: %d", id)
		err = errors.New(errMessage)
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 0,
			Data:     nil,
			Stats:    nil,
			Error:    &errMessage,
		}
	} else {
		mutationResponse = &gqlModel.MutationResponse{
			StatusOk: 1,
			Stats: &gqlModel.MutationStats{
				DeleteCount: response.RowCount,
			},
			Data: &gqlModel.MutationContent{
				ID:          id,
				ContentType: "Application",
				UpdatedAt:   response.UpdatedAt,
				DeletedAt:   response.UpdatedAt,
			},
			Error: nil,
		}
	}
	return mutationResponse, err
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*gqlModel.Job, error) {
	dbJobs, err := r.jobPortalUsecase.GetJobs(ctx)
	if err != nil {
		fmt.Printf("failed to fetch jobs: %v", err)
		return nil, err
	}
	jobs := make([]*gqlModel.Job, 0)
	for _, dbJob := range dbJobs {
		job := dbJob.ToGQL()
		jobs = append(jobs, job)
	}
	return jobs, nil
}

// Companies is the resolver for the companies field.
func (r *queryResolver) Companies(ctx context.Context) ([]*gqlModel.Company, error) {
	dbCompanies, err := r.jobPortalUsecase.GetCompanies(ctx)
	if err != nil {
		fmt.Printf("failed to fetch companies: %v", err)
		return nil, err
	}
	companies := make([]*gqlModel.Company, 0)
	for _, dbCompany := range dbCompanies {
		company := dbCompany.ToGQL()
		companies = append(companies, company)
	}
	return companies, nil
}

// Applicants is the resolver for the applicants field.
func (r *queryResolver) Applicants(ctx context.Context) ([]*gqlModel.Applicant, error) {
	dbApplicants, err := r.jobPortalUsecase.GetApplicants(ctx)
	if err != nil {
		fmt.Printf("failed to fetch applicants: %v", err)
		return nil, err
	}
	applicants := make([]*gqlModel.Applicant, 0)
	for _, dbApplicant := range dbApplicants {
		applicant := dbApplicant.ToGQL()
		applicants = append(applicants, applicant)
	}
	return applicants, nil
}

// Applications is the resolver for the applications field.
func (r *queryResolver) Applications(ctx context.Context) ([]*gqlModel.Application, error) {
	dbApplications, err := r.jobPortalUsecase.GetApplications(ctx)
	if err != nil {
		fmt.Printf("failed to fetch applications: %v", err)
		return nil, err
	}
	applications := make([]*gqlModel.Application, 0)
	for _, dbApplication := range dbApplications {
		application := dbApplication.ToGQL()
		applications = append(applications, application)
	}
	return applications, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*gqlModel.User, error) {
	dbUsers, err := r.jobPortalUsecase.GetUsers(ctx)
	if err != nil {
		fmt.Printf("failed to fetch users: %v", err)
		return nil, err
	}
	users := make([]*gqlModel.User, 0)
	for _, dbUser := range dbUsers {
		user := dbUser.ToGQL()
		users = append(users, user)
	}
	return users, nil
}

// ApplicationsByApplicantID is the resolver for the applicationsByApplicantId field.
func (r *queryResolver) ApplicationsByApplicantID(ctx context.Context, applicantID int64) ([]*gqlModel.Application, error) {
	applications, err := r.jobPortalUsecase.GetApplicationsByApplicantID(ctx, applicantID)
	if err != nil {
		return nil, err
	}
	gqlApplications := make([]*gqlModel.Application, 0)
	for _, application := range applications {
		gqlApp := application.ToGQL()
		gqlApplications = append(gqlApplications, gqlApp)
	}
	return gqlApplications, nil
}

// ApplicationsByJobID is the resolver for the applicationsByJobId field.
func (r *queryResolver) ApplicationsByJobID(ctx context.Context, jobID int64) ([]*gqlModel.Application, error) {
	applications, err := r.jobPortalUsecase.GetApplicationsByJobID(ctx, jobID)
	if err != nil {
		return nil, err
	}
	gqlApplications := make([]*gqlModel.Application, 0)
	for _, application := range applications {
		gqlApp := application.ToGQL()
		gqlApplications = append(gqlApplications, gqlApp)
	}
	return gqlApplications, nil
}

// JobsByCompanyID is the resolver for the jobsByCompanyId field.
func (r *queryResolver) JobsByCompanyID(ctx context.Context, companyID int64) ([]*gqlModel.Job, error) {
	jobs, err := r.jobPortalUsecase.GetJobsByCompanyID(ctx, companyID)
	if err != nil {
		return nil, err
	}
	gqlJobs := make([]*gqlModel.Job, 0)
	for _, job := range jobs {
		gqlJob := job.ToGQL()
		gqlJobs = append(gqlJobs, gqlJob)
	}
	return gqlJobs, nil
}

// Mutation returns gqlModel.MutationResolver implementation.
func (r *Resolver) Mutation() gqlModel.MutationResolver { return &mutationResolver{r} }

// Query returns gqlModel.QueryResolver implementation.
func (r *Resolver) Query() gqlModel.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
