# GraphQL schema example
#
# https://gqlgen.com/getting-started/


type Mutation {
  createJob(input: NewJob!): Job
  createCompany(input: NewCompany!): Company
  createApplicant(input: NewApplicant!): Applicant
  createUser(input: NewUser!): User
  createApplication(input: NewApplication!): Application

  updateJobById(id: ID!, job: UpdateJob!): MutationResponse!
  updateCompanyById(id: ID!, company: UpdateCompany!): MutationResponse!
  updateUserById(id: ID!, user: UpdateUser!): MutationResponse!
  updateApplicationById(id: ID!, application: UpdateApplication!): MutationResponse!

  deleteJobById(id: ID!): MutationResponse!
  deleteCompanyById(id: ID!): MutationResponse!
  deleteApplicantById(id: ID!): MutationResponse!
  deleteUserById(id: ID!): MutationResponse!
  deleteApplicationById(id: ID!): MutationResponse!
}

type Query {
  jobs: [Job!]!
  companies: [Company!]!
  applicants: [Applicant!]!
  applications: [Application!]!
  users: [User!]!
  applicationsByApplicantId(applicantId: ID!): [Application!]!
  applicationsByJobId(jobId: ID!): [Application!]!
  jobsByCompanyId(companyId: ID!): [Job!]!
}
