# GraphQL schema example
#
# https://gqlgen.com/getting-started/


type Mutation {
  createJob(input: NewJob!): Job
  createCompany(input: NewCompany!): Company
  createApplicant(input: NewApplicant!): Applicant
  createUser(input: NewUser!): User
  createApplication(input: NewApplication!): Application

  # TODO: refactor, extract id from update object
  updateJobById(input: UpdateJob!): Job
  updateCompanyById(input: UpdateCompany!): Company
  updateUserById(input: UpdateUser!): User
  updateApplicationById(input: UpdateApplication!): Application

  deleteJobById(input: ID!): DeletionStatus
  deleteCompanyById(input: ID!): DeletionStatus
  deleteApplicantById(input: ID!): DeletionStatus
  deleteUserById(input: ID!): DeletionStatus
  deleteApplicationById(input: ID!): DeletionStatus
}

type Query {
  jobs: [Job!]!
  companies: [Company!]!
  applicants: [Applicant!]!
  applications: [Application!]!
  users: [User!]!
  applicationsByApplicantId(applicantId: ID!): [Application!]!
  applicationsByJobId(jobId: ID!): [Application!]!
  jobsByCompanyId(companyId: ID!): [Job!]!
}
