package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/ni-tami/service/internal/graphql/model"
)

// User is the resolver for the user field.
func (r *applicantResolver) User(ctx context.Context, obj *model.Applicant) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Applicant is the resolver for the applicant field.
func (r *applicationResolver) Applicant(ctx context.Context, obj *model.Application) (*model.Applicant, error) {
	panic(fmt.Errorf("not implemented: Applicant - applicant"))
}

// Job is the resolver for the job field.
func (r *applicationResolver) Job(ctx context.Context, obj *model.Application) (*model.Job, error) {
	panic(fmt.Errorf("not implemented: Job - job"))
}

// User is the resolver for the user field.
func (r *companyResolver) User(ctx context.Context, obj *model.Company) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Company is the resolver for the company field.
func (r *jobResolver) Company(ctx context.Context, obj *model.Job) (*model.Company, error) {
	panic(fmt.Errorf("not implemented: Company - company"))
}

// Applicant returns model.ApplicantResolver implementation.
func (r *Resolver) Applicant() model.ApplicantResolver { return &applicantResolver{r} }

// Application returns model.ApplicationResolver implementation.
func (r *Resolver) Application() model.ApplicationResolver { return &applicationResolver{r} }

// Company returns model.CompanyResolver implementation.
func (r *Resolver) Company() model.CompanyResolver { return &companyResolver{r} }

// Job returns model.JobResolver implementation.
func (r *Resolver) Job() model.JobResolver { return &jobResolver{r} }

type applicantResolver struct{ *Resolver }
type applicationResolver struct{ *Resolver }
type companyResolver struct{ *Resolver }
type jobResolver struct{ *Resolver }
