package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/ni-tami/job-hunting-dummies-service/internal/graphql/model"
)

// User is the resolver for the user field.
func (r *applicantResolver) User(ctx context.Context, obj *model.Applicant) (*model.User, error) {
	user, err := r.jobPortalUsecase.GetUserByID(ctx, int64(obj.User.ID))
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Name:      user.Name,
		Username:  user.Username,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		DeletedAt: user.DeletedAt,
	}, nil
}

// Applicant is the resolver for the applicant field.
func (r *applicationResolver) Applicant(ctx context.Context, obj *model.Application) (*model.Applicant, error) {
	applicant, err := r.jobPortalUsecase.GetApplicantByID(ctx, int64(obj.Applicant.ID))
	if err != nil {
		return nil, err
	}
	return &model.Applicant{
		ID: applicant.ID,
		User: &model.User{
			ID: applicant.UserID,
		},
		CreatedAt: applicant.CreatedAt,
		UpdatedAt: applicant.UpdatedAt,
		DeletedAt: applicant.DeletedAt,
	}, nil
}

// Job is the resolver for the job field.
func (r *applicationResolver) Job(ctx context.Context, obj *model.Application) (*model.Job, error) {
	job, err := r.jobPortalUsecase.GetJobByID(ctx, int64(obj.Job.ID))
	if err != nil {
		return nil, err
	}
	return &model.Job{
		ID:        job.ID,
		Title:     job.Title,
		CreatedAt: job.CreatedAt,
		UpdatedAt: job.UpdatedAt,
		DeletedAt: job.DeletedAt,
	}, nil
}

// User is the resolver for the user field.
func (r *companyResolver) User(ctx context.Context, obj *model.Company) (*model.User, error) {
	user, err := r.jobPortalUsecase.GetUserByID(ctx, int64(obj.User.ID))
	if err != nil {
		return nil, err
	}
	return &model.User{
		ID:        user.ID,
		Name:      user.Name,
		Username:  user.Username,
		CreatedAt: user.CreatedAt,
		UpdatedAt: user.UpdatedAt,
		DeletedAt: user.DeletedAt,
	}, nil
}

// Company is the resolver for the company field.
func (r *jobResolver) Company(ctx context.Context, obj *model.Job) (*model.Company, error) {
	company, err := r.jobPortalUsecase.GetCompanyByID(ctx, int64(obj.Company.ID))
	if err != nil {
		return nil, err
	}
	// NOTE: if value for User ID is company.User.ID null pointer and cannot resolve user. WHy? See details later
	return &model.Company{
		ID: company.ID,
		User: &model.User{
			ID: company.UserID,
		},
		CompanyName: company.CompanyName,
		Website:     company.Website,
		Description: company.Description,
		CreatedAt:   company.CreatedAt,
		UpdatedAt:   company.UpdatedAt,
		DeletedAt:   company.DeletedAt,
	}, nil
}

// Applicant returns model.ApplicantResolver implementation.
func (r *Resolver) Applicant() model.ApplicantResolver { return &applicantResolver{r} }

// Application returns model.ApplicationResolver implementation.
func (r *Resolver) Application() model.ApplicationResolver { return &applicationResolver{r} }

// Company returns model.CompanyResolver implementation.
func (r *Resolver) Company() model.CompanyResolver { return &companyResolver{r} }

// Job returns model.JobResolver implementation.
func (r *Resolver) Job() model.JobResolver { return &jobResolver{r} }

type (
	applicantResolver   struct{ *Resolver }
	applicationResolver struct{ *Resolver }
	companyResolver     struct{ *Resolver }
	jobResolver         struct{ *Resolver }
)
