package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"

	"github.com/ni-tami/job-hunting-dummies-service/internal/graphql/model"
)

// User is the resolver for the user field.
func (r *applicantResolver) User(ctx context.Context, obj *model.Applicant) (*model.User, error) {
	return &model.User{
		ID:        obj.User.ID,
		Name:      obj.User.Name,
		Username:  obj.User.Username,
		CreatedAt: obj.User.CreatedAt,
		UpdatedAt: obj.User.UpdatedAt,
		DeletedAt: obj.User.DeletedAt,
	}, nil
}

// Applicant is the resolver for the applicant field.
func (r *applicationResolver) Applicant(ctx context.Context, obj *model.Application) (*model.Applicant, error) {
	return &model.Applicant{
		ID: obj.Applicant.ID,
		User: &model.User{
			ID:       obj.Applicant.User.ID,
			Username: obj.Applicant.User.Username,
		},
		CreatedAt: obj.CreatedAt,
		UpdatedAt: obj.UpdatedAt,
		DeletedAt: obj.DeletedAt,
	}, nil
}

// Job is the resolver for the job field.
func (r *applicationResolver) Job(ctx context.Context, obj *model.Application) (*model.Job, error) {
	return &model.Job{
		ID:        obj.Job.ID,
		Title:     obj.Job.Title,
		CreatedAt: obj.CreatedAt,
		UpdatedAt: obj.UpdatedAt,
		DeletedAt: obj.DeletedAt,
	}, nil
}

// User is the resolver for the user field.
func (r *companyResolver) User(ctx context.Context, obj *model.Company) (*model.User, error) {
	return &model.User{
		ID:        obj.User.ID,
		Name:      obj.User.Name,
		Username:  obj.User.Username,
		CreatedAt: obj.User.CreatedAt,
		UpdatedAt: obj.User.UpdatedAt,
		DeletedAt: obj.User.DeletedAt,
	}, nil
}

// Company is the resolver for the company field.
func (r *jobResolver) Company(ctx context.Context, obj *model.Job) (*model.Company, error) {
	return &model.Company{
		ID: obj.Company.ID,
		User: &model.User{
			ID: obj.Company.User.ID,
		},
		CompanyName: obj.Company.CompanyName,
		Website:     obj.Company.Website,
		Description: obj.Company.Description,
		CreatedAt:   obj.Company.CreatedAt,
		UpdatedAt:   obj.Company.UpdatedAt,
		DeletedAt:   obj.Company.DeletedAt,
	}, nil
}

// Applicant returns model.ApplicantResolver implementation.
func (r *Resolver) Applicant() model.ApplicantResolver { return &applicantResolver{r} }

// Application returns model.ApplicationResolver implementation.
func (r *Resolver) Application() model.ApplicationResolver { return &applicationResolver{r} }

// Company returns model.CompanyResolver implementation.
func (r *Resolver) Company() model.CompanyResolver { return &companyResolver{r} }

// Job returns model.JobResolver implementation.
func (r *Resolver) Job() model.JobResolver { return &jobResolver{r} }

type applicantResolver struct{ *Resolver }
type applicationResolver struct{ *Resolver }
type companyResolver struct{ *Resolver }
type jobResolver struct{ *Resolver }
