syntax = "proto3";

import "google/protobuf/timestamp.proto";

option go_package = "github.com/ni-tami/job-hunting-dummies-service/pb/job_hunting_dummies";
package job_hunting_dummies.v0;


message CreateUserRequest {
    string username = 1;
    string name = 2;
}

message CreateUserResponse {
    int64 id = 1;
    string username = 2;
    string name = 3;
    google.protobuf.Timestamp created_at = 4;
}

message CreateCompanyRequest {
    string company_name = 1;
    CreateUserRequest user = 2;
    string description = 3;
    string website = 4;
}

message CreateCompanyResponse {
    int64 id = 1;
    int64 user_id = 2;
    string company_name = 3;
    string description = 4;
    string website = 5;
    google.protobuf.Timestamp created_at = 6;
}

message GetRandomSourceCompaniesRequest {
    int32 size = 1;
}

message GetRandomSourceCompaniesResponse {
    // TODO paging
    int32 size = 1;
    repeated SourceCompanyReponse companies = 2;
}

message SourceCompanyReponse {
    int64 source_id = 1;
    string name = 3;
    string long_description = 4;
    string website = 5;
}
